"""
Firebase Configuration Helper
This script helps you retrieve your Firebase configuration
"""

print("=" * 60)
print("🔥 FIREBASE CONFIGURATION HELPER")
print("=" * 60)
print()
print("Your Firebase Project ID: stem-c0eca")
print()
print("📋 STEP 1: Get Your Firebase Configuration")
print("-" * 60)
print()
print("Option A - Using Firebase CLI (Recommended):")
print("   Run this command in your terminal:")
print("   firebase apps:sdkconfig web")
print()
print("Option B - Using Firebase Console:")
print("   1. Go to: https://console.firebase.google.com/")
print("   2. Select project: stem-c0eca")
print("   3. Click the gear icon ⚙️ (Project Settings)")
print("   4. Scroll down to 'Your apps' section")
print("   5. Click '</>' (Web app) or 'Add app' if none exists")
print("   6. Copy the firebaseConfig object")
print()
print("=" * 60)
print("📋 STEP 2: After You Get the Config")
print("-" * 60)
print()
print("1. Open: static/js/firebase-config.js")
print("2. Replace the commented lines with your actual config")
print("3. It should look like this:")
print()
print("   const firebaseConfig = {")
print("       apiKey: 'AIzaSy...',")
print("       authDomain: 'stem-c0eca.firebaseapp.com',")
print("       databaseURL: 'https://stem-c0eca.firebaseio.com',")
print("       projectId: 'stem-c0eca',")
print("       storageBucket: 'stem-c0eca.appspot.com',")
print("       messagingSenderId: '123456789',")
print("       appId: '1:123456789:web:abc123'")
print("   };")
print()
print("4. Save the file")
print("5. Run: python build.py")
print("6. Run: firebase deploy")
print()
print("=" * 60)
print("✅ Need Help?")
print("-" * 60)
print("If you can't find your config, you can also create a new web app:")
print("   firebase init hosting")
print()
print("Or visit the direct link:")
print("https://console.firebase.google.com/project/stem-c0eca/settings/general")
print("=" * 60)
